name: Build and Push Release

on: [push]

jobs:
  build-and-push-release:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack_start
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":pray:  *Deployment to staging environment started by ${{ github.actor }} please stand by* \n>_*Branch:*_ `${{ github.ref_name }}` <${{ github.event.pull_request.html_url || github.event.head_commit.url }} | (commit)>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


      - name: Send custom JSON data to Slack workflow
        id: slack_finish
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment to staging.perchwell.com completed with the status `${{ job.status }}` *\n>_*Branch:*_  `${{ github.ref_name }}` <${{ github.event.pull_request.html_url || github.event.head_commit.url }} | (commit)>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 
