name: Build and Push Release

on: [push]

jobs:
  build-and-push-release:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
          # if: steps.changed-files-specific.outputs.any_changed == 'true'
          id: prep
          run: |
            SHA=$(echo $GITHUB_SHA | head -c7)
            GITHUB_ACTOR =$(echo $GITHUB_ACTOR)
            GITHUB_REF_NAME=(echo $GITHUB_REF_NAME)

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":pray:  *Deployment to staging environment started by $GITHUB_ACTOR, please stand by* \n>Branch: $GITHUB_REF_NAME <$SHA|*commit*>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
