name: Build and Push Release

on: [push]

jobs:
  build-and-push-release:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":pray:  *Deployment to staging environment started by ${{ github.actor }} please stand by* \n>_*Branch:*_ ${{ github.ref_name }} (<${{ github.server_url }}/${{ github.repository }}/${{ github.sha }} )| commit>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
